export const STACKS = {
  'node-basic': {
    name: 'Node.js Basic',
    description: 'Sederhana untuk script kecil atau automation',
    folders: ['src', 'tests'],
    files: {
      'src/index.js': '// Entry point\nconsole.log("Hello from Corox Basic!");',
      '.gitignore': 'node_modules\n.env\ndist',
      'README.md': '# Project Basic\nGenerated by Corox CLI'
    },
    dependencies: []
  },
  'express-enterprise': {
    name: 'Express.js Enterprise',
    description: 'Struktur Clean Architecture untuk skala besar',
    folders: [
      'src/domain/entities',
      'src/domain/repositories',
      'src/application/use-cases',
      'src/infrastructure/database',
      'src/infrastructure/web',
      'src/interfaces/controllers',
      'src/interfaces/middlewares',
      'tests/unit',
      'tests/integration',
      'config'
    ],
    files: {
      'src/index.ts': 'import app from "./infrastructure/web/app.js";\napp.listen(3000, () => console.log("Server running on port 3000"));',
      'config/env.ts': 'export const config = { port: process.env.PORT || 3000 };',
      '.gitignore': 'node_modules\n.env\ndist\n.DS_Store',
      'README.md': '# Enterprise Project\nArchitecture: Clean Architecture\nGenerated by Corox CLI'
    },
    dependencies: ['express', 'dotenv', 'cors', 'helmet']
  },
  'ts-library': {
    name: 'TypeScript Library',
    description: 'Struktur optimal untuk membuat package NPM',
    folders: ['src', 'tests', 'docs'],
    files: {
      'src/index.ts': 'export const hello = () => "Hello from Corox Lib!";',
      'tsconfig.json': '{\n  "compilerOptions": {\n    "target": "ESNext",\n    "module": "NodeNext",\n    "outDir": "./dist",\n    "declaration": true\n  }\n}',
      '.gitignore': 'node_modules\ndist\n.env',
      'README.md': '# TS Library\nGenerated by Corox CLI'
    },
    dependencies: []
  }
};
